# Generated by Django 5.2.11 on 2026-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=500)),
                ('question_ru', models.CharField(max_length=500)),
                ('question_en', models.CharField(blank=True, max_length=500)),
                ('answer_uz', models.TextField()),
                ('answer_ru', models.TextField()),
                ('answer_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['order'],
            },
        ),
    ]
