# Generated by Django 5.2.11 on 2026-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('masketniy_setka', 'Masketniy setka'), ('jalyuzi', 'Jalyuzi'), ('kabinka', 'Dushovoy kabinka'), ('remont', 'Remont')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Gaplashilmagan'), ('in_progress', 'Telefon qilinmoqda'), ('confirmed', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20)),
                ('taken_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
