# Generated by Django 5.2.11 on 2026-03-07 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('masketnitsa', 'Masketnitsa'), ('jalyuzi', 'Jalyuzi'), ('kabinka', 'Dushovoy Kabinka')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('meta_title_uz', models.CharField(blank=True, max_length=200)),
                ('meta_title_ru', models.CharField(blank=True, max_length=200)),
                ('meta_title_en', models.CharField(blank=True, max_length=200)),
                ('meta_description_uz', models.TextField(blank=True)),
                ('meta_description_ru', models.TextField(blank=True)),
                ('meta_description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label_uz', models.CharField(blank=True, max_length=100)),
                ('price_label_ru', models.CharField(blank=True, max_length=100)),
                ('price_label_en', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['order'],
            },
        ),
    ]
