# Generated by Django 5.2.11 on 2026-03-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='specialists/')),
                ('name', models.CharField(max_length=100)),
                ('position_uz', models.CharField(max_length=200)),
                ('position_ru', models.CharField(blank=True, max_length=200)),
                ('position_en', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mutaxassis',
                'verbose_name_plural': 'Mutaxassislar',
                'ordering': ['order'],
            },
        ),
    ]
